### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [bircni/ParkenUlmAndroid#34]
Looking at the diff: https://monitor.f-droid.org/builds/log/development.parkenulm/13#site-footer

I guess the published APK: https://github.com/bircni/ParkenUlmAndroid/releases/tag/v2.0.1

was not built from the same commit: https://github.com/bircni/ParkenUlmAndroid/commit/1632e549585fe2643976266a2ca7dfefc6c81594

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/2ec2359469b8f8986996d55d43efcc7cacbd9093

**Comment by licaon-kter** [comment]
Looking at the huge diff: https://gitlab.com/fdroid/fdroiddata/-/jobs/4383939960#L343 are you sure this APK: https://github.com/bircni/ParkenUlmAndroid/releases/tag/v2.0.1 is built from https://github.com/bircni/ParkenUlmAndroid/commit/1632e549585fe2643976266a2ca7dfefc6c81594 ?

**Comment by bircni** [comment]
weird - I pulled everything new from github and rebuilt it xD

**Comment by licaon-kter** [comment]
Still :( https://gitlab.com/fdroid/fdroiddata/-/jobs/5576865228#L2190

**Comment by licaon-kter** [comment]
bumped commit to match yours: https://gitlab.com/fdroid/fdroiddata/-/commit/e85fe039853c76b96b784b1c585562a229041253

**Comment by bircni** [comment]
@licaon-kter done.
